[package]
name = "meloweb"
version = "0.1.0"
authors = ["Vi <violet@hey.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "~0.9.0"
melo = { path="../../melo", default-features = false }

[patch.crates-io]
rimd = { path = "./rimd" }
